### ISSUE TITLE
四人本绘制无效

### ISSUE THREAD

**Issue by xxf0818** [RedAsteroid/FFXIV_Triggers#3]
我还以为6.5更新后mlm的高级触发器用不了了，后面也换了最新版本的鲶鱼精跟MoreLog都无法实现绘制，更换了splatoon的官库，国服防ban库，mlm分享6.5本地版都不行，后面换到了阿洛的宝宝椅高级触发器也无法正常实现四人本绘制
不知道是不是个例

**Comment by RedAsteroid** [comment]
请先浏览README文档的使用方法自查设置情况是否有遗漏。
如果仍有问题，根据您的描述，建议您检查以下内容:
-  检查ACT是否正常运行
-  检查Splatoon插件是否正常运行或启用了多个同名插件
-  检查Splatoon插件设置中，"使用WebAPI" 勾选Port后显示为: "http://127.0.0.1:47774/"
-  检查其他插件的监听端口是否与Splatoon插件监听端口重复

**Comment by xxf0818** [comment]
![9U09TTUQ5)49P`6RNPCHTG](https://github.com/RedAsteroid/FFXIV_Triggers/assets/143591386/abfb25c4-1197-481b-85bb-5b5ffaf5e339)
![}{M }SICU`K{1AFX)X9SB0M](https://github.com/RedAsteroid/FFXIV_Triggers/assets/143591386/adfbec7f-650c-49e9-890c-6c459d41dd8d)
![8 WLHKECKXK~%QH}}8F84VH](https://github.com/RedAsteroid/FFXIV_Triggers/assets/143591386/a04e63c4-051e-4c51-aa61-16daf3519e4e)
![D E2`24HS@`)7YM(AZ69EZK](https://github.com/RedAsteroid/FFXIV_Triggers/assets/143591386/28920c02-ae3b-4b35-9cb1-e0ace7d0ef1b)
![G 12 J585O}4ZO}IMZ(R$WN](https://github.com/RedAsteroid/FFXIV_Triggers/assets/143591386/6c0a8a62-d9fe-43ca-92d5-9d6e8170a698)
![MHD5}0MGFX0O$~6 ZVG3RQ7](https://github.com/RedAsteroid/FFXIV_Triggers/assets/143591386/305c5a72-8bbd-413c-a2bf-baf852096c76)
![S$@%6 @(R~~4{ $ HH3PI2](https://github.com/RedAsteroid/FFXIV_Triggers/assets/143591386/a98b9571-a3ff-4050-a365-76e741da22e2)
![T3Y5BY1TKYJ5(}3$~_W_6$6](https://github.com/RedAsteroid/FFXIV_Triggers/assets/143591386/dc463245-cd55-4922-afbf-8f87dbcbe4ec)

**Comment by xxf0818** [comment]
![image](https://github.com/RedAsteroid/FFXIV_Triggers/assets/143591386/25dd96b5-65e5-4869-9fa3-d5ecba1fbf2c)
我另外用咖啡搭载阿洛的宝宝椅也无法实现四人本绘制，我问了我另一个挂友，发现他也无法实现绘制了6.5

**Comment by RedAsteroid** [comment]
感谢您提供的信息，您可以尝试在Triggernometry插件导入一个测试用触发:

```
<?xml version="1.0"?>
<TriggernometryExport Version="1">
  <ExportedTrigger Enabled="true" Name="测试绘制47774| /e test" Id="952c41b6-ae41-49bf-9e2d-2f5dd6187ba0" RegularExpression="^.{14} ChatLog 00:0038::test$">
    <Actions>
      <Action OrderNumber="1" JsonEndpointExpression="http://127.0.0.1:47774/?namespace=self&amp;destroyAt=5000,COMBAT_EXIT,TERRITORY_CHANGE" JsonPayloadExpression="{&quot;Name&quot;:&quot;1&quot;,&quot;type&quot;:1,&quot;radius&quot;:2.0,&quot;color&quot;:3372220415,&quot;overlayBGColor&quot;:4278190080,&quot;overlayTextColor&quot;:4294967295,&quot;overlayVOffset&quot;:1.0,&quot;thicc&quot;:4.0,&quot;overlayText&quot;:&quot;这是一个测试&quot;,&quot;refActorType&quot;:1}" ActionType="GenericJson">
        <Condition Enabled="false" Grouping="And" />
      </Action>
      <Action OrderNumber="1" UseTTSTextExpression="测试" ActionType="UseTTS">
        <Condition Enabled="false" Grouping="Or" />
      </Action>
    </Actions>
    <Condition Enabled="false" Grouping="Or" />
    <Conditions />
  </ExportedTrigger>
</TriggernometryExport>
```

您需要在聊天频道输入/e test来触发，这个触发将绘制一个圆形于玩家自身5秒。
如果绘制有效说明通信正常，您可以尝试移除我的触发器重新导入来修复。
如果绘制无效，则可能是其他潜在的问题。

但无论结果如何，我可能无法解决您的问题，它可能是有很多未知原因造成的，很抱歉。

**Comment by xxf0818** [comment]
非常感谢作者大大的回复
![image](https://github.com/RedAsteroid/FFXIV_Triggers/assets/143591386/35135dce-8da3-4f7a-9db8-846e2ff69bf1)
c测试有效，而且我刚才打了把
![image](https://github.com/RedAsteroid/FFXIV_Triggers/assets/143591386/d5d03579-ff12-443f-adc6-13a22f4db39d)
已经有明显的绘制了，但是我没有变动任何插件，我怀疑本次问题是我通过勾选取消再勾选
![image](https://github.com/RedAsteroid/FFXIV_Triggers/assets/143591386/e2276b77-f02d-40fb-8f33-20dff4aead2d)
解决的，尚不知道是为何导致于这种情况，我也与我朋友即使进行了反馈，再次非常感谢

**Comment by xxf0818** [comment]
我用了FAKENAME,不怕
