### ISSUE TITLE
大佬，默认会不会发送信息，或者标记给队友？

### ISSUE THREAD

**Issue by kindgxs** [RedAsteroid/FFXIV_Triggers#4]
大佬，默认会不会发送信息，或者标记给队友？

**Comment by RedAsteroid** [comment]
当前提交文件全部为默语，触发器只有P12S、豪神提供鲶鱼精邮差标记功能并默认为本地标记。
初次导入不做任何修改的情况下，默认**不会**发送聊天到小队频道，队友也看不到标记。

**Comment by kindgxs** [comment]
谢谢大佬

**Comment by kindgxs** [comment]
大佬，极北造物院 boss1默认指挥勾上的
